# https://alacritty.org/config-alacritty.html

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
startup_mode = "Maximized"
#decorations = "ButtonLess"
decorations = "Full"
decorations_theme_variant = "Dark"

option_as_alt = "Both"

[font]
#normal.family = "Hack Nerd Font Mono"
normal.family = "MesloLGS Nerd Font Mono"
size = 16

[selection]
save_to_clipboard = true

#[mouse]
#hide_when_typing = true

[keyboard]
bindings = [
# Shift|Control|Super|Command|Alt|Option
# cmd/alt readline on Mac
{ key= "f", mods= "Command", chars= "\u001Bf" }, # Skip word right, overwriting search
{ key= "b", mods= "Command", chars= "\u001Bb" }, # Skip word left, overwrithing search
{ key= "d", mods= "Command", chars= "\u001Bd" }, # Skip word left
{ key = "f", mods = "Control", action = "SearchForward" },
{ key = "b", mods = "Control", action = "SearchBackward" },
{ key = "+", mods = "Command|Shift", action = "IncreaseFontSize" },
{ key = "-", mods = "Command", action = "DecreaseFontSize" },
{ key = "t", mods = "Command", action = "CreateNewTab" },
]

